FROM alpine@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce

RUN apk add --no-cache \
    bash=5.2.37-r0 \
    coreutils=9.7-r1 \
    iproute2=6.15.0-r0 \
    jq=1.8.1-r0 \
    netcat-openbsd=1.229.1-r0 \
    nftables=1.1.3-r0 \
    tcpdump=4.99.5-r1

CMD ["sleep", "infinity"]
