set skip on lo0

users      = "10.10.10.0/27"
servers    = "10.10.20.0/24"
monitoring = "10.10.60.0/25"
management = "10.10.70.0/28"
internal   = "10.10.0.0/16"
lan        = "{ vtnet1, vtnet2, vtnet3, vtnet4 }"

nat on vtnet0 from $users      to any -> (vtnet0)
nat on vtnet0 from $servers    to any -> (vtnet0)
nat on vtnet0 from $monitoring to any -> (vtnet0)
nat on vtnet0 from $management to any -> (vtnet0)

block all


# Internet
pass in  on $lan from $internal to ! $internal keep state
pass out on vtnet0 all keep state

# Monitoring -> redes monitoradas
pass in quick on vtnet3 from $monitoring to $users keep state
pass in quick on vtnet3 from $monitoring to $servers keep state

# Management -> todas as redes internas
pass in quick on vtnet4 from $management to $internal keep state

# Saída necessária para encaminhamento autorizado
pass out on vtnet1 all keep state
pass out on vtnet2 all keep state
pass out on vtnet3 all keep state
pass out on vtnet4 all keep state
