hostname="s2-freebsd-router"

ifconfig_vtnet0="DHCP"

ifconfig_vtnet1="inet 10.10.10.1 netmask 255.255.255.224"
ifconfig_vtnet2="inet 10.10.20.1 netmask 255.255.255.0"
ifconfig_vtnet3="inet 10.10.60.1 netmask 255.255.255.128"
ifconfig_vtnet4="inet 10.10.70.1 netmask 255.255.255.240"

gateway_enable="YES"
ifconfig_DEFAULT="DHCP inet6 accept_rtadv"
growfs_enable="YES"
pf_enable="YES"
pf_rules="/etc/pf.conf"
sshd_enable="YES"
